name: Terraform Pipeline

on:
  pull_request:
    branches: [ dev, main ]

  push:
    branches: [ dev, main ]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format & Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
        run: terraform plan -out=tfplan.bin -no-color

      # =========================
      # APPLY ל-DEV אחרי merge
      # =========================
      - name: Terraform Apply (DEV)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
        run: terraform apply -auto-approve tfplan.bin

      # =========================
      # APPLY ל-MAIN ידני בלבד
      # =========================
      - name: Terraform Apply (MAIN - Manual)
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
        run: terraform apply -auto-approve tfplan.bin