name: Terraform Pipeline

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: sa-iac@project-a44aae81-833b-4037-891.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform plan -out=tfplan.bin -no-color

      # מפרסם את תוצאות הפלן בתוך ה-PR כדי שתוכלי לראות מה עומד לקרות
      - name: Publish Plan to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "### Terraform Plan Result 🚀\n_Validated and ready for review!_"
            })

      # הגנה מפני מחיקות אוטומטיות ב-Dev
      - name: Check for destructive changes
        id: check
        run: |
          DESTROY=$(terraform show -json tfplan.bin | jq -r '
            [ .resource_changes[]? 
              | select( any(.change.actions[]; . == "delete") 
                        or any(.change.actions[]; . == "replace") )
            ] | length > 0
          ')
          echo "destroy=$DESTROY" >> $GITHUB_OUTPUT


      # 1. בראנץ' DEV - רץ אוטומטית מיד אחרי המיזוג (Push)
      # - name: Terraform Apply to DEV (Automatic)
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/dev' && steps.check.outputs.destroy == 'false'
      #   run: terraform apply -auto-approve tfplan.bin

      # 2. בראנץ' MAIN - ירוץ אך ורק אם לחצת על הכפתור הידני ב-GitHub (Workflow Dispatch)
      - name: Terraform Apply to MAIN (Manual Approval)
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan.bin